<a href="https://colab.research.google.com/github/pokeychip19946/python-basics/blob/master/Day_1_1_Data_Manipulation_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("We are learning Numpy")   ### shift + enter

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
#### Create an array with Numpy(1D)
a = np.array([1,2,3,4,5])
print(a)

In [ ]:
#### Create an array with Numpy(2D)
a = np.array([[1,2,3,4,5],[4,5,6,7,8],[6,4,2,4,5]])
print(a)

In [ ]:
a.ndim

In [ ]:
#### Create an array with Numpy(3D)
b = np.array([[[1,2,3,4,5],[4,5,6,7,8],[6,4,2,4,5]]])
print(b)

In [ ]:
b.ndim

In [ ]:
a.shape

In [ ]:
a

In [ ]:
b.shape

In [ ]:
b

In [ ]:
len(a)

In [ ]:
len(b)

In [ ]:
print(a,b)

In [ ]:
a.size

15

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.sum()

66

In [ ]:
a.mean()

In [ ]:
a

In [ ]:
a.sum(axis=1)  ### row wise addition

In [ ]:
a.sum(axis=0)  ### column wise addition

In [ ]:
b

In [ ]:
b.sum(axis=1)

In [ ]:
b.sum(axis=0)

In [ ]:
a.min()

1

In [ ]:
a

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [6, 4, 2, 4, 5]])

In [ ]:
a.max()

In [ ]:
a.argmin()

In [ ]:
a.argmax()

In [ ]:
a = np.array([[1,2,3,4,5],[4,5,6,7,8],[6,4,2,4,5],[60,40,2,40,50],[6,40,20,40,5]])
print(a)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 6  4  2  4  5]
 [60 40  2 40 50]
 [ 6 40 20 40  5]]


In [ ]:
#### Picking elements from array
a[1]

array([4, 5, 6, 7, 8])

In [ ]:
a[1:]

array([[ 4,  5,  6,  7,  8],
       [ 6,  4,  2,  4,  5],
       [60, 40,  2, 40, 50],
       [ 6, 40, 20, 40,  5]])

In [ ]:
a[1:4]

array([[ 4,  5,  6,  7,  8],
       [ 6,  4,  2,  4,  5],
       [60, 40,  2, 40, 50]])

In [ ]:
a[1,2]

6

In [ ]:
a[1][2]

6

In [ ]:
a[:,2]

array([ 3,  6,  2,  2, 20])

In [ ]:
a

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 6,  4,  2,  4,  5],
       [60, 40,  2, 40, 50],
       [ 6, 40, 20, 40,  5]])

In [ ]:
a[1:5,3]

array([ 7,  4, 40, 40])

In [ ]:
b

array([[[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8],
        [6, 4, 2, 4, 5]]])

In [ ]:
b[0][1][2]

6

In [ ]:
a

In [ ]:
a[:,2]

In [ ]:
a[2]

In [ ]:
a.shape

In [ ]:
a.reshape(25,1)

In [ ]:
a = a.reshape(1,5,5)

In [ ]:
a

In [ ]:
### Zero Matrix
z = np.zeros((4,5))
z

In [ ]:
### Ones Matrix
o = np.ones((4,5))
o

In [ ]:
### Identity Matrix
i = np.identity(5)
i

In [ ]:
i.astype('int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
### Generate some equidistant numbers between a range
a = np.linspace(1,100,30)
a

In [ ]:
a = np.linspace(1,100,10)
a

In [ ]:
a = np.linspace(1,100,100)
a

In [ ]:
b = np.arange(1,101,5)
b

In [ ]:
### random numbers
a = np.random.randint(1,100)

In [ ]:
np.random.randint(1,101,5)

In [ ]:
a

In [ ]:
### Seed Concept
np.random.seed(3)
np.random.randint(1,101)

In [ ]:
np.random.randint(1,100,(3,4))

In [ ]:
np.random.random(10)

In [ ]:
np.random.random((4,4))

array([[0.55277195, 0.30636063, 0.58661997, 0.27492011],
       [0.45460777, 0.75766525, 0.81757073, 0.25758529],
       [0.89306511, 0.71842202, 0.0206145 , 0.14271733],
       [0.32530618, 0.8089292 , 0.39899095, 0.42470161]])

In [ ]:
a = np.linspace(1,100,30)
a

array([  1.        ,   4.4137931 ,   7.82758621,  11.24137931,
        14.65517241,  18.06896552,  21.48275862,  24.89655172,
        28.31034483,  31.72413793,  35.13793103,  38.55172414,
        41.96551724,  45.37931034,  48.79310345,  52.20689655,
        55.62068966,  59.03448276,  62.44827586,  65.86206897,
        69.27586207,  72.68965517,  76.10344828,  79.51724138,
        82.93103448,  86.34482759,  89.75862069,  93.17241379,
        96.5862069 , 100.        ])

In [ ]:
np.round(a)

array([  1.,   4.,   8.,  11.,  15.,  18.,  21.,  25.,  28.,  32.,  35.,
        39.,  42.,  45.,  49.,  52.,  56.,  59.,  62.,  66.,  69.,  73.,
        76.,  80.,  83.,  86.,  90.,  93.,  97., 100.])

In [ ]:
np.round(a,2)

array([  1.  ,   4.41,   7.83,  11.24,  14.66,  18.07,  21.48,  24.9 ,
        28.31,  31.72,  35.14,  38.55,  41.97,  45.38,  48.79,  52.21,
        55.62,  59.03,  62.45,  65.86,  69.28,  72.69,  76.1 ,  79.52,
        82.93,  86.34,  89.76,  93.17,  96.59, 100.  ])

In [ ]:
np.trunc(a)

array([  1.,   4.,   7.,  11.,  14.,  18.,  21.,  24.,  28.,  31.,  35.,
        38.,  41.,  45.,  48.,  52.,  55.,  59.,  62.,  65.,  69.,  72.,
        76.,  79.,  82.,  86.,  89.,  93.,  96., 100.])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,20,30],[40,50,60],[6,7,8]])

In [ ]:
a.shape

(2, 3)

In [ ]:
b.shape

(3, 3)

In [ ]:
np.dot(a,b)

array([[108, 141, 174],
       [276, 372, 468]])

In [ ]:
np.dot(b,a.T)

array([[140, 320],
       [320, 770],
       [ 44, 107]])

In [ ]:
np.pi

3.141592653589793

In [ ]:
np.cos(90)

-0.4480736161291701

In [ ]:
np.tan(90)

-1.995200412208242

In [ ]:
np.sin(90)

0.8939966636005579

In [ ]:
np.cos(np.pi/2)

6.123233995736766e-17

In [ ]:
np.exp(10)

22026.465794806718

In [ ]:
np.log(10)

2.302585092994046

In [ ]:
np.log10(10)

1.0

In [ ]:
np.cos(np.degrees(180))

-0.8205810566088714

In [ ]:
a = np.array([[1,2,3,4,5],[4,5,6,7,8],[6,4,2,4,5],[60,40,2,40,50],[6,40,20,40,5]])
print(a)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 6  4  2  4  5]
 [60 40  2 40 50]
 [ 6 40 20 40  5]]


In [ ]:
a[:,1:3] 

array([[ 2,  3],
       [ 5,  6],
       [ 4,  2],
       [40,  2],
       [40, 20]])