<a href="https://colab.research.google.com/github/pokeychip19946/python-basics/blob/master/Day_9_Simple_Neural_Network_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
inputs = np.array([[0,0,1],[1,1,0],[0,1,1],[1,0,1],[1,1,1]])
outputs = np.array([[0],[1],[0],[1],[1]])

In [ ]:
inputs

array([[0, 0, 1],
       [1, 1, 0],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [ ]:
outputs

array([[0],
       [1],
       [0],
       [1],
       [1]])

In [ ]:
np.random.seed(10)
weights = np.random.random((3,1))
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [ ]:
sum = np.dot(inputs,weights) + 0.02
sum

array([[0.65364823],
       [0.81207259],
       [0.67440018],
       [1.42496888],
       [1.44572083]])

In [ ]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [ ]:
sigmoid(5)

0.9933071490757153

In [ ]:
sum = np.dot(inputs,weights) + 0.02
ypred = sigmoid(sum)
ypred

array([[0.65783211],
       [0.69255099],
       [0.66248773],
       [0.8061162 ],
       [0.80933899]])

In [ ]:
sum = np.dot(inputs,weights) + 0.02
ypred = sigmoid(sum)
error = outputs - ypred
error

array([[-0.65783211],
       [ 0.30744901],
       [-0.66248773],
       [ 0.1938838 ],
       [ 0.19066101]])

In [ ]:
def gradient(x):
  return x * (1-x)

In [ ]:
sum = np.dot(inputs,weights) + 0.02
ypred = sigmoid(sum)
error = outputs - ypred
adjustment = error * gradient(ypred)   ### gradient descent
weights = weights + np.dot(inputs.T,adjustment)  ## back propagation
error

array([[-0.65783211],
       [ 0.30744901],
       [-0.66248773],
       [ 0.1938838 ],
       [ 0.19066101]])

In [ ]:
inputs.T.shape

(3, 5)

In [ ]:
adjustment.shape

(5, 1)

In [ ]:
for i in range(1500):
  sum = np.dot(inputs,weights) + 0.02
  ypred = sigmoid(sum)
  error = outputs - ypred
  adjustment = error * gradient(ypred)   ### gradient descent
  weights = weights + np.dot(inputs.T,adjustment)   ## back propagation
error

array([[-0.02563487],
       [ 0.00054907],
       [-0.02078144],
       [ 0.01689394],
       [ 0.02085879]])

In [ ]:
ypred.round()

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.]])

In [ ]:
weights

array([[ 7.70230157],
       [-0.21485846],
       [-3.65818916]])